name: Deploy Mountains

on: [push]

defaults:
  run:
    shell: bash
    working-directory: mountains

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Install Surge
        run: npm install --global surge

      - name: Surge deploy
        run: surge ./dist react-scroll-parallax-mountains.surge.sh --token ${{ secrets.SURGE_TOKEN }}
